function [phi_d] = ac_phi_dot_simulink(u_gen)
% Usage: [phi_d] = ac_phi_dot_simulink(u_gen)
%        u_gen: [q, q_des]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

q = u_gen(1:4);
phi_d = zeros(2,1);
q_des = u_gen(5:10);
phi_d(1) = -(50*q_des(3) - 50*q(3) + 10*q_des(5) + (981*cos(q(1)))/10)*(5*q(1) + q(3) - 5*q_des(1) - q_des(3));
phi_d(2) = - (50*q(1) + 10*q(3) - 50*q_des(1) - 10*q_des(3))*((981*cos(q(1) + q(2)))/100 + (981*cos(q(1)))/100 + (cos(q(2)) + 1)*(5*q_des(4) - 5*q(4) + q_des(6)) + (2*cos(q(2)) + 2)*(5*q_des(3) - 5*q(3) + q_des(5)) - 2*q(4)*sin(q(2))*(5*q_des(1) - 5*q(1) + q_des(3)) - q(4)*sin(q(2))*(5*q_des(2) - 5*q(2) + q_des(4))) - (50*q(2) + 10*q(4) - 50*q_des(2) - 10*q_des(4))*(5*q_des(4) - 5*q(4) + q_des(6) + (981*cos(q(1) + q(2)))/100 + (cos(q(2)) + 1)*(5*q_des(3) - 5*q(3) + q_des(5)) + q(3)*sin(q(2))*(5*q_des(1) - 5*q(1) + q_des(3)));
