function [tauc] = classical_joint_planar_robot_simulink(u_gen)
% Usage: [tauc] = classical_joint_planar_robot_simulink(u_gen)
%        u_gen: [q, eps, q_des, m1, m2, a1, a2, b1, b2, g]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

q = u_gen(1:4);
eps = u_gen(5:6);
tauc = zeros(2,1);
q_des = u_gen(7:12);
m1 = u_gen(13);
m2 = u_gen(14);
a1 = u_gen(15);
a2 = u_gen(16);
b1 = u_gen(17);
b2 = u_gen(18);
g = u_gen(19);

tauc(1) = 1000*eps(1) - 2540*q(1) - (502*q(3))/5 + 2540*q_des(1) + (502*q_des(3))/5;
tauc(2) = 1000*eps(2) - 2540*q(2) - (502*q(4))/5 + 2540*q_des(2) + (502*q_des(4))/5;
