function [tauc] = ct_gravit_planar_robot_simulink(u_gen)
% Usage: [tauc] = ct_gravit_planar_robot_simulink(u_gen)
%        u_gen: [q, q_des, m1, m2, a1, a2, b1, b2, g]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

q = u_gen(1:4);
tauc = zeros(2,1);
q_des = u_gen(5:10);
m1 = u_gen(11);
m2 = u_gen(12);
a1 = u_gen(13);
a2 = u_gen(14);
b1 = u_gen(15);
b2 = u_gen(16);
g = u_gen(17);

tauc(1) = 100*q_des(1) - 20*q(3) - 100*q(1) + 20*q_des(3) + (981*cos(q(1) + q(2)))/100 + (981*cos(q(1)))/50;
tauc(2) = 100*q_des(2) - 20*q(4) - 100*q(2) + 20*q_des(4) + (981*cos(q(1) + q(2)))/100;
