function [tauc] = smc_planar_robot_simulink(u_gen)
% Usage: [tauc] = smc_planar_robot_simulink(u_gen)
%        u_gen: [q, q_des, m1, m2, a1, a2, b1, b2, g]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

q = u_gen(1:4);
tauc = zeros(2,1);
q_des = u_gen(5:10);
m1 = u_gen(11);
m2 = u_gen(12);
a1 = u_gen(13);
a2 = u_gen(14);
b1 = u_gen(15);
b2 = u_gen(16);
g = u_gen(17);

tauc(1) = (2943*cos(q(1) + q(2)))/400 - 10*sign(125*q(1) + 5*q(3) - 125*q_des(1) - 5*q_des(3)) + (2943*cos(q(1)))/200 + (25*q_des(3) - 25*q(3) + q_des(5))*((a1^2*m1)/4 + (a1^2*m2)/4 + (a2^2*m2)/4 + (a1*a2*m2*cos(q(2)))/2) - (3*q(4)*sin(q(2))*(25*q_des(1) - 25*q(1) + q_des(3)))/2 - (3*q(4)*sin(q(2))*(25*q_des(2) - 25*q(2) + q_des(4)))/4 + (a2*m2*(a2 + a1*cos(q(2)))*(25*q_des(4) - 25*q(4) + q_des(6)))/4;
tauc(2) = (2943*cos(q(1) + q(2)))/400 - 10*sign(125*q(2) + 5*q(4) - 125*q_des(2) - 5*q_des(4)) + (3*q(3)*sin(q(2))*(25*q_des(1) - 25*q(1) + q_des(3)))/4 + (a2^2*m2*(25*q_des(4) - 25*q(4) + q_des(6)))/4 + (a2*m2*(a2 + a1*cos(q(2)))*(25*q_des(3) - 25*q(3) + q_des(5)))/4;
