function [tauc] = ac_controller_simulink(u_gen)
% Usage: [tauc] = ac_controller_simulink(u_gen)
%        u_gen: [q, q_des, m1, m2]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

q = u_gen(1:4);
tauc = zeros(2,1);
q_des = u_gen(5:10);
m1 = u_gen(11);
m2 = u_gen(12);
tauc(1) = 500*q_des(1) - 100*q(3) - 500*q(1) + 100*q_des(3) + (m1 + 2*m2 + 2*m2*cos(q(2)))*(5*q_des(3) - 5*q(3) + q_des(5)) + (981*m1*cos(q(1)))/100 + (981*m2*(cos(q(1) + q(2)) + cos(q(1))))/100 + m2*(cos(q(2)) + 1)*(5*q_des(4) - 5*q(4) + q_des(6)) - 2*m2*q(4)*sin(q(2))*(5*q_des(1) - 5*q(1) + q_des(3)) - m2*q(4)*sin(q(2))*(5*q_des(2) - 5*q(2) + q_des(4));
tauc(2) = 500*q_des(2) - 100*q(4) - 500*q(2) + 100*q_des(4) + m2*(5*q_des(4) - 5*q(4) + q_des(6)) + (981*m2*cos(q(1) + q(2)))/100 + m2*(cos(q(2)) + 1)*(5*q_des(3) - 5*q(3) + q_des(5)) + m2*q(3)*sin(q(2))*(5*q_des(1) - 5*q(1) + q_des(3));
