function [qdes] = trajectory3_planar_robot_simulink(u_gen)
% Usage: [qdes] = trajectory3_planar_robot_simulink(u_gen)
%        u_gen: [t]
% generated by planar_robot_2dof.m for planar_robot_simulation.slx

t = u_gen(1);
qdes = zeros(6,1);
qdes(1) = sin(t);
qdes(2) = sin(t);
qdes(3) = cos(t);
qdes(4) = cos(t);
qdes(5) = -sin(t);
qdes(6) = -sin(t);
